"""One-Page Kaizen data (Denso format, creative-idea-kaizen skill) for the 8 Kaizen candidates listed in the
Kaizen_IoT_CBM sheets of AM_Standard_Hydraulic_Unit.xlsx (H-K1…H-K4) and AM_Standard_Pneumatic_System.xlsx (P-K1…P-K4).

Tags: [FACT] = PDF page of the JIPM-Solutions deck or the AM Standard · [INFERENCE: H/M/L] · [PROPOSED] = target ·
[DATA REQUIRED] = plant value · [ASSUME] = example value. Case references are real cards of the skill corpus.
"""

PLACE = "(ระบุ Line จริง) — DD-MMM-YY"


def check(yokoten_dated=0, quantified=1, closeup=1):
    """Self-Check 20 items, scored honestly: the Yokoten date stays 0 until the plant fills it in."""
    return {
        "r1": [["ZH-A ตัวเลขติด Tag ครบ", 1], ["ZH-B ไม่ invent Spec", 1], ["ZH-C Why ≥ 3 ชั้น", 1], ["ZH-E Physics Validity", 1],
               ["ZH-G Spring Rule", 1], ["ZH-H ไม่มี Motor/PLC เป็นแรงขับ", 1], ["ZH-I Prompt ตรงฟิสิกส์", 1], ["ZH-K Confidence ประกาศ", 1]],
        "r2": [["ECR ก่อนกลไก", 1], ["力・構造・原理 ครบ", 1], ["Point ①-⑤ มีเหตุผล", 1], ["Fail-safe ระบุ", 1],
               ["苦労点 Dual Layer", 1], ["Quantified + สูตรเงิน", quantified], ["Yokoten + วันที่", yokoten_dated]],
        "r3": [["Prompt ครบ Before/After/Close-up", closeup], ["หลักการฝังใน Prompt", 1], ["Excel 4 Sheets", 1],
               ["เปิดได้จริง (verify แล้ว)", 1], ["One-Page ครบ 8 ช่อง Denso", 1]],
    }


STYLE_A = "Clean Japanese kaizen training manual illustration, simple line art, round-headed worker character"
STYLE_B = "Japanese engineering textbook diagram, clear black outlines, flat gray fills"
COLOR = "Limited palette: 70% white-gray, 25% steel blue-gray, 5% {accent} accent only on {where}. White background, no photorealism, no text other than the labels specified."

# summary-sheet fields: before/after minutes per occurrence, occurrences per year, cost upper bound (THB)
CASES = [
    # ======================================================================== HYDRAULIC
    {"id": "H-K1", "sys": "hyd", "std": "H01 / H25 (C · I)", "kind": "SOC", "priority": "P1", "resp": "Leader",
     "before_min": 3, "after_min": 1, "occ": 312, "cost_max": 1000, "confidence": "Level 3 · มีเคสหลักการใกล้เคียง (KRK-BLUE-252)",
     "title": "แผ่นซับใต้จุดรั่ว 『ผ้าขาวฟ้องรั่ว』",
     "summary": "ทำให้รอยรั่วน้ำมันไฮดรอลิก 『เห็นทันที!』『รู้ตำแหน่ง!』『เช็ดน้อยลง!』 · Confidence: Level 3 — หลักการ P2+P11 มีเคสจริง (KRK-BLUE-252) แต่ยังไม่ทดลองที่เครื่องนี้",
     "workflow": ["① หยุดปั๊มหลังเลิกงาน", "② เช็ดถัง ท่อ ข้อต่อ ทั้ง Unit ด้วยผ้า", "③ ไล่หาคราบ/หยดใหม่ทีละจุด แล้วดูพื้นรอบเครื่อง"],
     "problem_quant": "เช็ด+หาจุดรั่ว ~3 นาที/วัน [INFERENCE: M] · รั่ว 1 หยด/10 วินาที = 0.42 L/วัน = 151 L/ปี/จุด [FACT PDF p.13]",
     "ideas": ["อยากเห็นหยดน้ำมันใหม่โดยไม่ต้องเช็ดทั้ง Unit", "อยากรู้ทันทีว่ารั่วจากจุดไหน", "อยากให้น้ำมันไม่ลงพื้น (ลื่น · ติดไฟได้ p.5)"],
     "mechanism": "ถาดตื้น + แผ่นซับน้ำมันสีขาว ติดหมายเลขจุด ใต้จุดเสี่ยงรั่ว → หยดใหม่ทิ้งรอยเข้มบนพื้นขาว เห็นได้จากทางเดิน ไม่ใช้พลังงาน [PROPOSED]",
     "points": [
         ("Point ① 力 กำลัง", "แรงโน้มถ่วงพาหยดน้ำมันลงแผ่นซับเอง — ไม่ต้องมีแหล่งพลังงาน"),
         ("Point ② 構造 โครงสร้าง", "A ถาดตื้นใต้ข้อต่อ · Relief valve · Solenoid valve · Dust seal กระบอกสูบ  B แผ่นซับสีขาว  C ป้ายหมายเลขจุด H-1…H-n ตรงกับแผนที่จุดรั่ว"),
         ("Point ③ 原理 หลักการ", "ความต่างสีขาว/น้ำมันเข้ม = ตรวจที่ปลายทางของปรากฏการณ์ (P2) + สถานะเห็นได้ (P11) · ‘ขาวสะอาด’ คือ Standard ที่ทำให้เห็นปัญหา (ID-3)"),
         ("Point ④ Fail-safe", "แผ่นอิ่มตัว/ไม่ได้เปลี่ยน → คราบเต็มแผ่น เห็นได้ชัด = สัญญาณให้เปลี่ยนแผ่นและแจ้งช่าง · ถาดกันน้ำมันลงพื้นแม้แผ่นเต็ม"),
         ("Point ⑤ 苦労点", "(A) ต้องวางใต้แนวหยดจริง ไม่ใช่ใต้ชิ้นส่วน — น้ำมันไหลตามผิวท่อก่อนหยด  (B) เลือกแผ่นที่ดูดน้ำมันแต่ไม่ดูดน้ำ และถาดต้องไม่ขวางงานถอดซ่อม")],
     "cost": "~500–1,000 บาท/Unit [INFERENCE: M]",
     "result": "เช็ด/หาจุดรั่ว 3 → 1 นาที/วัน [PROPOSED] = (3−1) × 26 วัน × 12 เดือน = 624 นาที/ปี (10.4 ชม.) × ค่าแรง [DATA REQUIRED] + น้ำมันที่ไม่สูญเสีย 151 L/ปี/จุด × ราคา [DATA REQUIRED] · S: พื้นไม่ลื่น · C: น้ำมัน",
     "yokoten": ["Gearbox / ปั๊มหล่อลื่นในไลน์ " + PLACE, "Hydraulic unit เครื่องอื่น " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "2D side view", "3:2", "manual whole-unit wiping hides new leaks",
          STYLE_A + ", flat 2D side view. A worker crouching beside a hydraulic power unit (oil tank, pump, valve block, pipes), wiping every pipe with a rag and searching for fresh oil drops with a flashlight, worried face with sweat drops. Old dark oil stains on the floor and on the gray machine body make new drops invisible. Caption box: '3 min/day wiping + searching; 1 drop every 10 s = 151 L/year'. Red X on the stained floor. " + COLOR.format(accent="red", where="the stained floor")),
         ("A1 After Overview", "B Technical Textbook", "Isometric", "3:2", "gravity carries each drop onto a white pad; contrast shows the leak point (direct phenomenon detection)",
          STYLE_B + ", isometric three-quarter view. A hydraulic power unit with shallow drip trays and white oil-absorbent pads placed directly under the leak-risk points. Thin vertical dashed arrows show oil drops falling by gravity from a pipe fitting onto the white pad, leaving one dark spot. Component labels with leader lines: A = drip tray, B = white absorbent pad, C = point number tag H-1 to H-4, D = relief valve, E = solenoid valve, F = cylinder dust seal. " + COLOR.format(accent="orange", where="the dark oil spot on pad H-2")),
         ("A2 Point Close-up", "B Technical Textbook", "Cross-section", "1:1", "drop follows the pipe surface then falls by gravity; pad placed under the true drip line",
          "Cutaway cross-section technical diagram, square format. Close-up of a hydraulic pipe fitting with an O-ring above a white absorbent pad in a shallow tray. A thin oil film runs along the underside of the pipe and drips from its lowest point, not from the fitting itself; a dashed vertical line marks the true drip line and the pad is centered on it. Labels: A = fitting, B = O-ring, C = drip point, D = white pad, E = tray lip. Hatching on cut surfaces. " + COLOR.format(accent="orange", where="the oil spot on the pad"))],
     "principles": [
         ("Idea-Design", "ID-3", "ต้องมี Standard จึงเห็นปัญหา", "แผ่นขาว = สภาพปกติที่มองเห็นได้ หยดใหม่จึงโดดออกมา", "KT2 p.14", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "Eliminate รั่วที่ต้นเหตุ (O-ring/ข้อต่อ) โดย PM ทำคู่กัน · ระหว่างนั้นการตรวจยังจำเป็น → Reduce เวลาหา → Change วิธีเห็น", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไมช้า? ต้องเช็ดทั้ง Unit ก่อน → ทำไม? คราบเก่ากลืนหยดใหม่ → ทำไม? ไม่มีพื้นอ้างอิงที่ทำให้หยดใหม่ต่างจากปกติ", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("Karakuri P1-P24", "P2 + P11", "ตรวจที่ปรากฏการณ์ + สถานะเห็นได้", "หยดน้ำมันทิ้งรอยบนแผ่นขาวตรงจุดที่เกิด", "karakuri-kaizen-design v18.2", "[FACT]"),
         ("Case reference", "KRK-BLUE-252", "Signal inversion ทำรอยรั่วให้เห็นชัด", "หลักการเดียวกัน: เปลี่ยนการเปลี่ยนสีจาง ๆ ให้เป็นสัญญาณที่เห็นทันที", "JMAC Blue p.252", "[FACT]"),
         ("Source fact", "PDF p.13", "1 หยด/10 วินาที = 151 L/ปี", "ใช้คำนวณผลน้ำมันที่ไม่สูญเสีย", "Equipment Skills Training – Hydraulic", "[FACT]")],
     "selfcheck": check()},

    {"id": "H-K2", "sys": "hyd", "std": "H12 / H17 / H21 (T)", "kind": "HTA", "priority": "P1", "resp": "Operator",
     "before_min": 3, "after_min": 0.5, "occ": 52, "cost_max": 300, "confidence": "Level 4 · วิธีมาตรฐานที่ใช้แพร่หลาย (PT-3)",
     "title": "Match mark ที่ Lock nut · โบลต์ 『เส้นตรง = แน่น』",
     "summary": "ตรวจความหลวมของ Lock nut Relief valve · โบลต์ Solenoid valve · โบลต์กระบอกสูบ 『ด้วยตา!』『ใน 0.5 นาที!』『ไม่ต้องใช้ประแจ!』 · Confidence: Level 4",
     "workflow": ["① เดินไปทีละจุด: Relief valve · Solenoid valve · กระบอกสูบ", "② ลองขันด้วยมือ/ประแจทีละตัว", "③ ไม่รู้ว่าตัวไหนเคยคลายหรือขันซ้ำแล้ว"],
     "problem_quant": "ลองขันทีละตัว ~3 นาที/ครั้ง [INFERENCE: M] · Lock nut Relief หลวม → ค่าตั้งแรงดันเปลี่ยน = ความผิดปกติที่พบมากที่สุด [FACT PDF p.17]",
     "ideas": ["อยากรู้ว่าน็อตคลายหรือไม่โดยไม่ต้องแตะ", "อยากเห็นได้จากจุดยืนตรวจ", "อยากให้ทุกคนตัดสินได้เหมือนกัน ไม่พึ่งความรู้สึกมือ"],
     "mechanism": "ขันตาม Torque แล้วลากเส้น Paint marker พาดน็อต → แหวน → ตัวเรือน (合いマーク = Match mark) · น็อตหมุนเมื่อใด เส้นเยื้องทันที [PROPOSED]",
     "points": [
         ("Point ① 力 กำลัง", "ไม่มีแหล่งพลังงาน — การหมุนของน็อตเองคือตัวแสดงผล (หมุน = เส้นเยื้อง)"),
         ("Point ② 構造 โครงสร้าง", "A Lock nut Relief valve  B โบลต์ฐาน Solenoid valve  C โบลต์/น็อตกระบอกสูบ · เส้นสีเดียวพาดต่อเนื่อง 3 ชิ้น · สีตามผู้ขัน (AM เหลือง / PM แดง *)"),
         ("Point ③ 原理 หลักการ", "ตรวจที่ปรากฏการณ์ (การหมุน) โดยตรง P2 + Visual P11 — ‘อย่าวัด จงกำหนด’ (PT-3)"),
         ("Point ④ Fail-safe", "เส้นเลือน/ทาสีทับ = ถือว่าไม่ผ่านตรวจ → ขันตาม Torque แล้วลากใหม่ · ห้ามลากเส้นใหม่โดยไม่ขัน"),
         ("Point ⑤ 苦労点", "(A) Lock nut Relief ต้องคลายเมื่อปรับตั้ง → ลากเส้นใหม่ทุกครั้งโดยผู้ได้รับมอบหมาย  (B) เลือก Paint marker ทนน้ำมันไฮดรอลิกและความร้อน ไม่ร่อนเมื่อเช็ด")],
     "cost": "~100–300 บาท (Paint marker ทนน้ำมัน) [INFERENCE: M]",
     "result": "3 → 0.5 นาที/ครั้ง [PROPOSED] = (3−0.5) × 52 สัปดาห์ = 130 นาที/ปี × ค่าแรง [DATA REQUIRED] · Lock nut Relief ตรวจได้ใน 5 วินาทีทุกวัน → ป้องกันค่าตั้งแรงดันเปลี่ยน (p.17) · Q: แรงดันคงที่",
     "yokoten": ["Regulator Lock nut ระบบลม (P-K3) " + PLACE, "Cushion valve Lock nut กระบอกสูบ (p.11) " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "2D side view", "3:2", "checking tightness by hand feel, bolt by bolt",
          STYLE_A + ", flat 2D side view. A worker walking between a relief valve, a solenoid valve block and a hydraulic cylinder, trying each nut and bolt with a wrench, unsure face with sweat drops and a question mark. Dashed line shows the walking path between the three points. Caption box: '3 min per check, by hand feel'. Red X on the wrench. " + COLOR.format(accent="red", where="the wrench")),
         ("A1 After Overview", "B Technical Textbook", "Isometric", "3:2", "match mark: one straight paint line across nut, washer and body; any rotation breaks the line",
          STYLE_B + ", isometric three-quarter view. A relief valve with handle and lock nut, a solenoid valve on its manifold, and cylinder mounting bolts, each marked with one straight yellow paint line running across nut, washer and body. All lines are continuous except one lock nut whose line segment is offset, highlighted. Component labels with leader lines: A = relief valve lock nut, B = solenoid valve bolts, C = cylinder bolts, D = paint line. An eye symbol shows inspection from standing position. " + COLOR.format(accent="orange", where="the offset line segment")),
         ("A2 Point Close-up", "B Technical Textbook", "Top view", "1:1", "nut rotation of a few degrees shifts the line segment on the nut away from the line on the body",
          "Technical diagram, square format, top view of a hexagon nut on a washer and body. Left half: straight paint line continuous across nut, washer and body, labeled 'OK'. Right half: the nut rotated about 15 degrees counter-clockwise (loosening direction), small curved arrow showing the rotation, the line segment on the nut now offset from the body line, labeled 'NG'. Labels: A = nut, B = washer, C = body, D = paint line. Flat grays. " + COLOR.format(accent="orange", where="the offset segment on the NG nut"))],
     "principles": [
         ("Idea Pattern", "PT-3", "Visual Control ‘อย่าวัด จงกำหนด’", "เปลี่ยนการลองขันเป็นการดูเส้น", "BP1 p.102", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "Eliminate การคลายถาวรต้องแก้ Design (EEM) · Relief ยังต้องปรับตั้งได้ → Change วิธีตรวจ", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไมต้องลองขัน? มองไม่ออกว่าน็อตหมุนแล้ว → ทำไม? ไม่มีจุดอ้างอิงตำแหน่งเดิม → ทำไม? มาตรฐานการขันไม่กำหนดสภาพหลังขันให้มองเห็น", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("Karakuri P1-P24", "P2 + P11", "ตรวจที่ปรากฏการณ์ + สถานะเห็นได้", "การหมุนของน็อตแสดงผลตัวเองบนเส้นสี", "karakuri-kaizen-design v18.2", "[FACT]"),
         ("Case reference", "KRK-CBI-154", "ความหลวมที่ซ่อนอยู่ แสดงให้เห็นในพริบตา", "แนวคิดเดียวกัน: ทำให้การเสื่อมที่มองไม่เห็นกลายเป็นสัญญาณที่ทุกคนอ่านได้", "JIPM Case Book 1 p.154", "[FACT]"),
         ("Source fact", "PDF p.17", "Lock nut หลวม → ค่าตั้ง Relief เปลี่ยน", "เป็นความผิดปกติหลักใน Daily inspection", "Equipment Skills Training – Hydraulic", "[FACT]")],
     "selfcheck": check()},

    {"id": "H-K3", "sys": "hyd", "std": "H07 / H10 (I)", "kind": "HTA", "priority": "P2", "resp": "Engineer",
     "before_min": 2, "after_min": 0, "occ": 312, "cost_max": 2000, "confidence": "Level 3 · หลักการ CBM ทั่วไป ยังไม่มี Baseline ของเครื่อง",
     "title": "IoT CBM สั่น + อุณหภูมิ ปั๊ม-มอเตอร์ 『ปั๊มฟ้องเอง』",
     "summary": "เฝ้าดูปั๊มไฮดรอลิก 『24 ชม.!』『ไม่ต้องเข้าใกล้ส่วนหมุน!』『เตือนก่อนเสีย!』 · ไฟฟ้าใช้เป็นสัญญาณเท่านั้น (P10) · Confidence: Level 3",
     "workflow": ["① ฟังเสียงปั๊ม 20 วินาทีแรกตอนเริ่มเดิน", "② เอาหลังมือแตะ Casing ปั๊ม/มอเตอร์ ใกล้ Coupling", "③ ตัดสินจากประสบการณ์ — Operator ใหม่แยกเสียงยาก"],
     "problem_quant": "~2 นาที/กะ [INFERENCE: M] · พื้นที่เสียงดัง · ใกล้ส่วนหมุน (危ない Abunai = อันตราย) · Cavitation/Aeration → ปั๊มเสีย (BD) [FACT PDF p.14]",
     "ideas": ["อยากรู้สภาพปั๊มโดยไม่ต้องเข้าใกล้ (TNL: ไม่ต้องเข้าใกล้)", "อยากเห็นแนวโน้มก่อนเสีย", "อยากให้ทุกคนตัดสินได้เหมือนกัน (TNL: ไม่ต้องวินิจฉัย)"],
     "mechanism": "What: Vibration sensor (MEMS) + Temperature probe (DS18B20) → ESP32 → ไฟเตือน 3 สีหน้าเครื่อง + บันทึก Trend · Where: Casing ปั๊ม และ Bearing housing มอเตอร์ · How: เทียบ Baseline ของเครื่องเอง [PROPOSED]",
     "points": [
         ("Point ① 力 กำลัง", "ไม่มีแรงขับ — ไฟฟ้าใช้ส่งสัญญาณเท่านั้น (P10) · ไม่แตะการทำงานของปั๊ม"),
         ("Point ② 構造 โครงสร้าง", "A Sensor สั่นที่ Casing ปั๊ม  B Temp probe ที่ Casing  C Sensor ที่ Bearing housing มอเตอร์ (ไม่ติดบน Coupling)  D ESP32 ในกล่องกันน้ำมัน  E ไฟเตือน 3 สี"),
         ("Point ③ 原理 หลักการ", "ตรวจที่ปรากฏการณ์ (สั่น/ร้อน) ณ จุดเกิด P2 · เกณฑ์เตือน = Baseline ช่วงปกติ 2 สัปดาห์ของเครื่องเอง ไม่ใช่ค่าตายตัว [PROPOSED]"),
         ("Point ④ Fail-safe", "ESP32/สายขาด → ไฟสถานะดับ = ‘ไม่รู้สถานะ’ → กลับไปฟัง/แตะตาม AM Standard · ไม่ลบข้อตรวจเดิมจนระบบนิ่ง 3 เดือน *"),
         ("Point ⑤ 苦労点", "(A) แยกการสั่นของปั๊มจากเครื่องข้างเคียงและพื้น  (B) ยึด Sensor แน่นบนผิวเรียบ (ยึดหลวม = อ่านผิด) และตั้งเกณฑ์จาก Baseline จริง")],
     "cost": "~1,000–2,000 บาท/ชุด [INFERENCE: M] ไม่รวมค่าแรงติดตั้ง",
     "result": "ฟัง+แตะ 2 → 0 นาที/กะ [PROPOSED] = 2 × 26 วัน × 12 เดือน × จำนวนกะ ([ASSUME] 1 กะ = 624 นาที/ปี) × ค่าแรง [DATA REQUIRED] · เตือนก่อน BD ปั๊ม (Cavitation/Aeration p.14) · S: ไม่ต้องเข้าใกล้ Coupling",
     "yokoten": ["มอเตอร์ปั๊มน้ำหล่อเย็น " + PLACE, "Compressor ระบบลม " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "2D side view", "3:2", "inspection by ear and hand next to a rotating coupling",
          STYLE_A + ", flat 2D side view. A new operator leaning close to a hydraulic pump and electric motor joined by a coupling, one hand cupped to the ear, the back of the other hand touching the pump casing, confused face with sweat drops, noise lines from nearby machines. Caption box: '2 min per shift; noisy area; close to rotating coupling'. Red X near the coupling. " + COLOR.format(accent="red", where="the coupling area")),
         ("A1 After Overview", "B Technical Textbook", "Isometric", "3:2", "sensors read vibration and temperature where they occur; electricity carries the signal only",
          STYLE_B + ", isometric three-quarter view. A hydraulic pump and motor on a base. A small vibration sensor and a temperature probe bolted on a flat area of the pump casing, another sensor on the motor bearing housing; thin cables run to a small sealed controller box, which drives a three-color signal tower at the operator aisle. No sensor on the coupling. Component labels with leader lines: A = pump vibration sensor, B = temperature probe, C = motor bearing sensor, D = controller box, E = signal tower. Thin dashed arrows show signal direction only. " + COLOR.format(accent="orange", where="the signal tower")),
         ("A2 Point Close-up", "B Technical Textbook", "Cross-section", "1:1", "rigid mounting on a flat machined pad transmits casing vibration to the sensor",
          "Cutaway cross-section technical diagram, square format. A vibration sensor screwed onto a flat machined pad on a pump casing wall, with a thin layer showing full metal contact; a second inset shows a loosely mounted sensor with a gap and wobble lines, marked with a red X. Labels: A = sensor, B = mounting stud, C = flat pad, D = casing wall. Small wave symbols show vibration passing from casing into sensor. " + COLOR.format(accent="orange", where="the contact surface"))],
     "principles": [
         ("Idea-Design", "TNL 5 / 6", "ไม่ต้องวินิจฉัย · ไม่ต้องเข้าใกล้", "ใช้ตั้งโจทย์: Operator ไม่ต้องแยกเสียงและไม่ต้องเข้าใกล้ Coupling", "BP1 p.14", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "Eliminate ทั้งหมดไม่ได้ (ยังต้องดูรั่ว) → Reduce การฟัง/แตะด้วย Sensor", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไม Operator ใหม่พลาด? แยกเสียงในพื้นที่ดังยาก → ทำไม? ใช้หูเป็นเครื่องวัด → ทำไม? สภาพปกติของปั๊มไม่เคยถูกบันทึกเป็นตัวเลข (ไม่มี Baseline)", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("Karakuri P1-P24", "P10 + P2", "ไฟฟ้าเฉพาะสัญญาณ · ตรวจที่ปรากฏการณ์", "Sensor ไม่ขับอะไร ใช้แจ้งเตือนเท่านั้น → ผ่าน ZH-H", "karakuri-kaizen-design v18.2", "[FACT]"),
         ("Case reference", "KRK-CBI-154", "ทางเลือกไม่ใช้ไฟ", "ตัวชี้แบบ Follower ที่แสดงการสั่นนอกฝาครอบ — ใช้ได้เมื่อการสั่นผิดปกติมีแอมพลิจูดชัด", "JIPM Case Book 1 p.154", "[INFERENCE: L]"),
         ("Source fact", "PDF p.14, p.18–19", "สาเหตุเสียงดัง/แรงดันไม่พอ · ตรวจเสียงและสัมผัส", "เป็นเกณฑ์เดิมที่ Sensor เข้ามาช่วย", "Equipment Skills Training – Hydraulic", "[FACT]")],
     "selfcheck": check()},

    {"id": "H-K4", "sys": "hyd", "std": "H05 (C)", "kind": "SOC", "priority": "P3", "resp": "PM",
     "before_min": 5, "after_min": 2, "occ": 52, "cost_max": None, "confidence": "Level 4 · ต้นฉบับแนะนำแบบ Oil bath สำหรับพื้นที่ฝุ่นมาก (p.22)",
     "title": "Air breather แบบ Oil bath 『ฝุ่นติดน้ำมัน ไม่เข้าถัง』",
     "summary": "ลดฝุ่นเข้าถังน้ำมันไฮดรอลิก 『ล้างห่างขึ้น!』『น้ำมันสะอาดนานขึ้น!』 · Confidence: Level 4 — ต้นฉบับ p.22 ระบุว่ามีประสิทธิภาพสูงในพื้นที่ฝุ่นมาก",
     "workflow": ["① ดูฝุ่นที่ไส้กรอง Air breather", "② สกปรก → ถอดล้างน้ำมันก๊าด หรือเปลี่ยน", "③ พื้นที่ฝุ่นมาก ไส้กรองตันเร็ว ต้องล้างบ่อย"],
     "problem_quant": "ล้าง ~5 นาที/ครั้ง สัปดาห์ละครั้ง [INFERENCE: M] · Breather ตัน → ปั๊มเสียงดัง [FACT PDF p.14] · ฝุ่นในน้ำมัน → Poppet/Spool สกปรกติด [FACT p.15–16]",
     "ideas": ["อยากให้ฝุ่นไม่เข้าถังตั้งแต่แรก", "อยากล้างห่างขึ้น", "อยากเห็นว่าเมื่อไรต้องเปลี่ยนน้ำมันในถ้วย"],
     "mechanism": "อากาศที่ถังหายใจเข้าต้องเลี้ยวผ่านผิวน้ำมันในถ้วยก่อนผ่านไส้กรอง → ฝุ่นติดน้ำมันและตกลงก้นถ้วย [FACT p.22: แบบ Oil bath]",
     "points": [
         ("Point ① 力 กำลัง", "ใช้การหายใจของถังเอง (อากาศเข้าเมื่อระดับน้ำมันลด) — ไม่มีแหล่งพลังงานใหม่"),
         ("Point ② 構造 โครงสร้าง", "A ถ้วยน้ำมัน (Oil bath)  B ไส้กรอง  C ฝาครอบ  D ทางอากาศเลี้ยวผ่านผิวน้ำมัน (ตามรูป a p.22)  E ขีดระดับน้ำมันในถ้วย"),
         ("Point ③ 原理 หลักการ", "อากาศเปลี่ยนทิศเร็ว ฝุ่นซึ่งหนักกว่าเลี้ยวไม่ทัน ชนผิวน้ำมันแล้วติด [INFERENCE: H] · กำจัดที่แหล่งสกปรก (SOC)"),
         ("Point ④ Fail-safe", "น้ำมันในถ้วยหมด → ยังกรองด้วยไส้กรองได้เหมือนแบบเดิม (ไม่แย่กว่าเดิม) · ขีดระดับทำให้เห็นก่อนหมด"),
         ("Point ⑤ 苦労点", "(A) ขนาดต้องให้ถังหายใจทันที่โหลดสูงสุด (p.22)  (B) ชนิด/ระดับน้ำมันในถ้วย และรอบเปลี่ยนตามฝุ่นจริงของพื้นที่")],
     "cost": "[DATA REQUIRED] ตามรุ่น/ขนาดถัง — ขอราคาผู้ผลิต",
     "result": "ล้างไส้กรอง 5 → 2 นาที/สัปดาห์ [PROPOSED] = (5−2) × 52 = 156 นาที/ปี × ค่าแรง [DATA REQUIRED] · Q: ฝุ่นในน้ำมันลด → วาล์วติดน้อยลง (p.15–16) · วัดผล: รอบล้างก่อน/หลัง",
     "yokoten": ["Breather ของ Gearbox ในพื้นที่ฝุ่น " + PLACE, "ถังน้ำมันหล่อลื่นอื่น " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "2D side view", "3:2", "dry filter breather clogs quickly in a dusty area",
          STYLE_A + ", flat 2D side view. A hydraulic oil tank in a dusty workshop with floating dust particles, a small dry filter-type air breather on the tank top clogged gray. A worker washing the filter element in a tray of kerosene with a nylon brush, tired face with sweat drops. Caption box: 'clogs fast; 5 min cleaning every week'. Red X on the clogged breather. " + COLOR.format(accent="red", where="the clogged breather")),
         ("A1 After Overview", "B Technical Textbook", "Isometric", "3:2", "the tank breathes in through an oil-bath breather that captures dust before the filter",
          STYLE_B + ", isometric three-quarter view. A hydraulic oil tank with an oil-bath air breather on the vent hole. Bold arrows show outside air entering under the cap, turning down over the oil surface in the cup, then up through the filter into the tank as the oil level falls. Dust dots drop into the oil. Component labels with leader lines: A = oil cup, B = filter, C = cap, D = air path, E = oil level mark. " + COLOR.format(accent="orange", where="the oil surface where dust is captured")),
         ("A2 Point Close-up", "B Technical Textbook", "Cross-section", "1:1", "sharp turn of the air stream makes heavier dust hit the oil surface (inertia)",
          "Cutaway cross-section technical diagram, square format. Oil-bath breather cut in half: air enters at the rim, flows down an annular passage, makes a sharp U-turn just above the oil surface, then rises through a filter element. Small dust particles follow straight lines into the oil while the air turns. Labels: A = cap, B = annular passage, C = oil surface, D = filter element, E = settled dust. Hatching on cut walls, curved arrows for air path. " + COLOR.format(accent="orange", where="the U-turn above the oil"))],
     "principles": [
         ("Source fact", "PDF p.22", "Air cleaner แบบ Oil bath มีประสิทธิภาพสูงเมื่อฝุ่นมาก", "เปลี่ยนชนิดตามต้นฉบับ", "Equipment Skills Training – Hydraulic", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "Eliminate แหล่งฝุ่น (ครอบ/ย้ายตำแหน่ง) ถ้าทำได้ดีที่สุด → ไม่ได้ จึง Change ชนิด Breather", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไมล้างบ่อย? ไส้กรองตันเร็ว → ทำไม? ฝุ่นรอบถังมาก ไส้กรองแห้งดักฝุ่นที่ผิวจนตัน → ทำไม? ชนิด Breather ไม่เหมาะกับสภาพแวดล้อม (Environment)", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("6 Factors", "Environment", "สภาพแวดล้อมเร่งการเสื่อม", "แก้ที่แหล่งสกปรก (SOC) ตาม AM Step 2", "AM Standard · Forced_Deterioration", "[FACT]"),
         ("Karakuri P1-P24", "P6", "Fluid conductor", "ใช้น้ำมันเป็นตัวดักฝุ่นในทางอากาศ", "karakuri-kaizen-design v18.2", "[INFERENCE: M]")],
     "selfcheck": check()},

    # ======================================================================== PNEUMATIC
    {"id": "P-K1", "sys": "pn", "std": "P03 (C)", "kind": "SOC + HTA", "priority": "P1", "resp": "PM",
     "before_min": 6, "after_min": 0, "occ": 312, "cost_max": 3000, "confidence": "Level 4 · กลไกลูกลอยมีเคสจริง (KRK-BLUE-282) + ต้นฉบับมี Auto drain",
     "title": "Auto drain แบบลูกลอย 『ลูกลอยระบายเอง』",
     "summary": "ระบายน้ำในลมอัดที่ Air filter 『อัตโนมัติ!』『ไม่ต้องก้มเปิดวาล์ว!』『ไม่ลืม!』 · ไม่ใช้ไฟ ใช้แรงลอยตัว + แรงดันลมในถ้วย · Confidence: Level 4",
     "workflow": ["① ต้นกะ ก้มดูระดับน้ำในถ้วยกรอง (ถ้วยอยู่ต่ำ/หลังเครื่อง)", "② เปิดวาล์ว Drain มือจนน้ำหมด", "③ ปิดวาล์ว — ทำทุกวัน ทุกชุด FRL"],
     "problem_quant": "~1.5 นาที/ชุด/วัน [INFERENCE: M] × 4 ชุด [ASSUME] = 6 นาที/วัน · กลางคืนอุณหภูมิลด เกิดน้ำทุกวัน [FACT PDF p.44] · น้ำ → วาล์ว/กระบอกสูบทำงานผิด สนิม ลมรั่ว [FACT p.41–42]",
     "ideas": ["อยากให้น้ำออกเองเมื่อถึงระดับ", "อยากไม่ต้องก้ม/เอื้อมใต้เครื่อง", "อยากไม่ลืม Drain ในวันที่ยุ่ง"],
     "mechanism": "ลูกลอยในถ้วยกรองยกตัวเมื่อน้ำถึงระดับ → เปิดวาล์วระบาย แรงดันลมในถ้วยดันน้ำออกเอง → น้ำลด ลูกลอยตก วาล์วปิด (ไม่ใช้ไฟ) [FACT: Auto drain p.45, p.49] [PROPOSED: ติดตั้ง]",
     "points": [
         ("Point ① 力 กำลัง", "แรงลอยตัว (Buoyancy) ของลูกลอย + แรงดันลมที่มีอยู่ในถ้วย (Borrowed power) — ไม่มีแหล่งพลังงานใหม่"),
         ("Point ② 構造 โครงสร้าง", "A ลูกลอย  B บ่าวาล์ว (Seat)  C ท่อระบายไปขวดรับน้ำ  D ขีดระดับน้ำสูงสุดบนถ้วย"),
         ("Point ③ 原理 หลักการ", "ระดับน้ำเป็นทั้งสัญญาณและแรงขับในตัวเดียว (P2 + P12: ลูกลอยเป็น Dog) — หลักเดียวกับ KRK-BLUE-282"),
         ("Point ④ Fail-safe", "ลูกลอยค้าง/บ่าวาล์วสกปรก → น้ำเกินขีดระดับ เห็นได้ → เปิด Drain มือ + แจ้งช่าง · ตรวจ Auto drain ทุก 3 เดือน (p.45)"),
         ("Point ⑤ 苦労点", "(A) สนิม/สิ่งสกปรกติดบ่าวาล์วทำให้ปิดไม่สนิท → ลมรั่วต่อเนื่อง  (B) ท่อระบายต้องนำน้ำไปขวดรับ ไม่ปล่อยลงพื้นหรือใส่ชิ้นงาน")],
     "cost": "~1,500–3,000 บาท/ชุด [INFERENCE: M] · นำร่อง 1 ชุดก่อน",
     "result": "Drain รายวัน 6 → 0 นาที/วัน [PROPOSED] = 6 × 26 วัน × 12 เดือน = 1,872 นาที/ปี (31 ชม.) [ASSUME 4 ชุด] × ค่าแรง [DATA REQUIRED] · Q: น้ำไม่เข้าวาล์ว · S: ไม่ต้องก้มเอื้อมใต้เครื่อง",
     "yokoten": ["ถังเก็บลม / จุดต่ำของท่อหลัก " + PLACE, "FRL ทุกเครื่องในไลน์ " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "2D side view", "3:2", "daily manual draining at a low, hard-to-reach bowl",
          STYLE_A + ", flat 2D side view. A worker kneeling and reaching under a machine frame to open the manual drain valve at the bottom of an air filter bowl full of water, water splashing into a small bucket, tired face with sweat drops. Caption box: '1.5 min per FRL per day x 4 sets'. Red X on the kneeling posture. " + COLOR.format(accent="red", where="the kneeling posture")),
         ("A1 After Overview", "B Technical Textbook", "Isometric", "3:2", "float rises with the water level and opens the drain; air pressure in the bowl pushes the water out",
          STYLE_B + ", isometric three-quarter view. An air filter, regulator and lubricator set mounted on a machine, the filter bowl fitted with a float-type auto drain and a clear hose leading down to a collection bottle on the floor. A bold arrow shows water pushed out through the hose by the air pressure inside the bowl. Component labels with leader lines: A = float, B = valve seat, C = drain hose, D = collection bottle, E = maximum water level mark. " + COLOR.format(accent="orange", where="the float")),
         ("A2 Point Close-up", "B Technical Textbook", "Cross-section", "1:1", "buoyancy lifts the float off the seat; falling level re-seats it (no electricity)",
          "Cutaway cross-section technical diagram, square format, two states side by side. Left: low water level, float resting on the valve seat, outlet closed. Right: water level high, float lifted by buoyancy, seat open, water flowing out of the outlet pushed by compressed air above. Upward straight arrow on the float, downward arrows on the air pressure, small flow arrows at the outlet. Labels: A = float, B = seat, C = outlet, D = compressed air, E = water. Hatching on cut surfaces. " + COLOR.format(accent="orange", where="the open seat in the right panel"))],
     "principles": [
         ("Source fact", "PDF p.44, p.45, p.49", "Drain วันละครั้ง · มี Auto drain · ตรวจ Auto drain ทุก 3 เดือน", "ใช้อุปกรณ์ที่ต้นฉบับกล่าวถึง", "Equipment Skills Training – Pneumatic", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "Eliminate น้ำที่ต้นทาง = P-K4 (ระดับระบบ) · ยังเหลือน้ำ → Reduce งานรายวันด้วยลูกลอย", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไมต้อง Drain ทุกวัน? น้ำสะสมทุกคืน → ทำไม? ลมอัดเย็นตัวตอนกลางคืน ไอน้ำกลั่นเป็นน้ำ (p.44) → ทำไม? ลมอัดจากต้นทางยังชื้น (ไม่มี Drain separator/Dryer พอ)", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("Karakuri P1-P24", "P12 + P2", "Actuator precision (Dog) · ตรวจที่ปรากฏการณ์", "ลูกลอยคือ Dog ที่สั่งเปิด-ปิดตามระดับน้ำ", "karakuri-kaizen-design v18.2", "[FACT]"),
         ("Case reference", "KRK-BLUE-282", "Float valve ระบายบ่อเอง ไม่ใช้ไฟ", "หลักการลูกลอยเปิด-ปิดตามระดับ", "JMAC Blue p.282", "[FACT]")],
     "selfcheck": check()},

    {"id": "P-K2", "sys": "pn", "std": "P01 / P18 (I)", "kind": "HTA", "priority": "P2", "resp": "Leader",
     "before_min": 15, "after_min": 5, "occ": 4, "cost_max": 300, "confidence": "Level 4 · วิธีหาลมรั่วด้วยน้ำสบู่ใช้แพร่หลาย",
     "title": "แผนที่ล่าลมรั่ว + Leak tag 『เจอครบ ไม่พลาดจุด』",
     "summary": "หาลมรั่วตาม Table 2 『เร็ว!』『ครบทุกจุด!』『เห็นผลบนบอร์ด!』 · Confidence: Level 4",
     "workflow": ["① ช่วงไลน์หยุด เดินฟังเสียงลมรั่วทีละจุด", "② พื้นที่เสียงดัง ได้ยินยาก", "③ จุดตรวจ 10+ จุดไม่มีลำดับ บางจุดถูกลืม"],
     "problem_quant": "~15 นาที/รอบ ทุก 3 เดือน [INFERENCE: M] · จุดตรวจ Table 2: ข้อต่อ 3 แบบ · Stop valve · สายยาง · Case/Drain cock · Relief hole · Lubricator · ช่องเติมน้ำมัน · Exhaust port · กระบอกสูบ [FACT PDF p.45]",
     "ideas": ["อยากรู้ว่าต้องตรวจจุดไหนบ้างโดยไม่ต้องจำ", "อยากเจอรั่วโดยไม่ต้องได้ยิน", "อยากเห็นจำนวนจุดรั่วลดลง"],
     "mechanism": "แผนที่ระบบลมติดหมายเลขจุดตามลำดับเส้นทางเดิน → ฉีดน้ำสบู่ (ฟองเกิดที่จุดรั่ว) → ติด Leak tag → นับจุดรั่วบนบอร์ด · พื้นที่ห้ามเปียกใช้ Ultrasonic leak detector [PROPOSED]",
     "points": [
         ("Point ① 力 กำลัง", "ลมที่รั่วเองสร้างฟองสบู่ — ไม่ต้องสร้างพลังงานใหม่"),
         ("Point ② 構造 โครงสร้าง", "A แผนที่ระบบลมที่ FRL  B ป้ายหมายเลขจุดที่ข้อต่อ  C ขวดฉีดน้ำสบู่  D Leak tag  E บอร์ดนับจุดรั่ว"),
         ("Point ③ 原理 หลักการ", "ทำปรากฏการณ์ที่มองไม่เห็นให้เห็น (ฟอง) P2 + เส้นทางตรวจลำดับเดียว กันลืมจุด"),
         ("Point ④ Fail-safe", "จุดที่ไม่ได้ตรวจ = ช่องในแผนที่ว่าง เห็นได้ · Tag ค้างเกิน 1 รอบ = แจ้งหัวหน้างาน"),
         ("Point ⑤ 苦労点", "(A) น้ำสบู่ใช้ไม่ได้กับจุดที่ห้ามเปียก (ไฟฟ้า/ชิ้นงาน) → ใช้ Ultrasonic  (B) วางเส้นทางให้จบในรอบเดียว ไม่เดินย้อน")],
     "cost": "น้ำสบู่ + ป้าย + Tag ~100–300 บาท [INFERENCE: M] · Ultrasonic ~5,000–20,000 บาท (ทางเลือก)",
     "result": "15 → 5 นาที/รอบ [PROPOSED] = (15−5) × 4 รอบ/ปี = 40 นาที/ปี · ผลหลัก: หาเจอครบ → ซ่อมครบ → ลมรั่วลด ภาระ Compressor ลด [INFERENCE: H] (ค่าไฟลมรั่ว [DATA REQUIRED])",
     "yokoten": ["ท่อลมหลักในอาคาร " + PLACE, "ท่อน้ำ/ไอน้ำ ตามรายการตรวจรวม (p.44) " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "Top view", "3:2", "searching leaks by ear without a route",
          STYLE_A + ", top-down floor plan view of a machine area with compressed-air pipes, valves and cylinders. A worker with a hand cupped to the ear wanders along a tangled dashed walking path that crosses itself, noise lines from machines, confused face. Several leak points marked with small hiss symbols are missed by the path. Caption box: '15 min per round; leaks hard to hear'. Red X on the tangled path. " + COLOR.format(accent="red", where="the missed leak symbols")),
         ("A1 After Overview", "B Technical Textbook", "Top view", "3:2", "a numbered route covers every Table 2 point once; soap bubbles show leaks",
          STYLE_B + ", top-down floor plan view. The same machine area with a single clean dashed route visiting numbered circles 1 to 10 at pipe fittings, stop valve, hose, filter case, regulator relief hole, lubricator, valve exhaust port and cylinder. A map board at the filter-regulator-lubricator set shows the same numbers. At point 6 soap bubbles mark a leak with a hanging tag. Component labels: A = map board, B = point number tag, C = soap spray bottle, D = leak tag, E = leak count board. " + COLOR.format(accent="orange", where="the bubbles and tag at point 6")),
         ("A2 Point Close-up", "B Technical Textbook", "2D side view", "1:1", "escaping air through a soap film forms growing bubbles exactly at the leak",
          "Technical diagram, square format, 2D side view of a threaded pipe fitting sprayed with soapy water. Small growing bubbles form at one thread gap where air escapes; a thin arrow shows air leaving the gap. A paper leak tag hangs on the pipe with a number. Labels: A = fitting, B = thread gap, C = soap bubbles, D = leak tag. " + COLOR.format(accent="orange", where="the bubbles"))],
     "principles": [
         ("Source fact", "PDF p.45", "ตรวจลมรั่วพร้อมรอบ 3 เดือน (Table 2)", "รายการจุดบนแผนที่มาจาก Table 2", "Equipment Skills Training – Pneumatic", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "Eliminate รั่ว = ซ่อม (PM) · Reduce ข้อต่อที่ไม่จำเป็น * · Change วิธีหา", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไมหาไม่ครบ? ได้ยินยากและจำจุดไม่ได้ → ทำไม? พึ่งหูและความจำ → ทำไม? ไม่มีรายการ/แผนที่ที่ทำให้เห็นสภาพที่ควรเป็น (ID-3)", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("Idea Pattern", "PT-3", "Visual Control", "แผนที่ + หมายเลขจุด + บอร์ดนับ", "BP1 p.102", "[FACT]"),
         ("Karakuri P1-P24", "P2 + P11", "ตรวจที่ปรากฏการณ์ + สถานะเห็นได้", "ฟองสบู่เกิดตรงจุดรั่ว · Tag บอกสถานะค้างซ่อม", "karakuri-kaizen-design v18.2", "[FACT]")],
     "selfcheck": check()},

    {"id": "P-K3", "sys": "pn", "std": "P06 / P02 (T)", "kind": "HTA", "priority": "P1", "resp": "Operator",
     "before_min": 2.5, "after_min": 0.5, "occ": 312, "cost_max": 300, "confidence": "Level 4 · วิธีมาตรฐานที่ใช้แพร่หลาย (PT-3)",
     "title": "Match mark Regulator · หน้าแปลน · ที่ยึดท่อ 『เส้นตรง = แน่น』",
     "summary": "ตรวจ Lock nut Regulator และโบลต์หน้าแปลน/ที่ยึดท่อ 『ด้วยตา!』『ใน 0.5 นาที!』 คู่กับแถบเขียวที่เกจ (p.39) · Confidence: Level 4",
     "workflow": ["① ลองขัน Lock nut Regulator ด้วยมือ", "② ลองขันโบลต์หน้าแปลน/ที่ยึดท่อใกล้เครื่อง", "③ ดูเกจว่าค่าตั้งเคลื่อนหรือไม่ — ทำทุกวัน"],
     "problem_quant": "~2.5 นาที/วัน [INFERENCE: M] · แรงสั่นทำให้ Handle หมุนเอง ค่าตั้งเคลื่อน [FACT PDF p.39] · ตรวจหน้าแปลน/โบลต์/ที่ยึดท่อ ทุกวัน [FACT p.44]",
     "ideas": ["อยากรู้ว่า Lock nut คลายโดยไม่ต้องแตะ", "อยากเห็นทุกจุดจากจุดยืนตรวจ", "อยากรู้ว่าค่าตั้งเคลื่อนก่อนแรงกระบอกสูบผิด"],
     "mechanism": "ขันแล้วลากเส้น Paint marker พาด Lock nut → ตัว Regulator และน็อตหน้าแปลน/ที่ยึดท่อ (合いマーク = Match mark) + แถบเขียวที่ค่าตั้งบนเกจ (p.39) [PROPOSED]",
     "points": [
         ("Point ① 力 กำลัง", "ไม่มีแหล่งพลังงาน — การหมุนของน็อต/Handle เองคือตัวแสดงผล"),
         ("Point ② 構造 โครงสร้าง", "A Lock nut Regulator  B โบลต์หน้าแปลน  C น็อตที่ยึดท่อ  D แถบเขียวบนเกจที่ค่าตั้ง · เส้นสีพาดต่อเนื่อง"),
         ("Point ③ 原理 หลักการ", "ตรวจที่ปรากฏการณ์ (การหมุน) P2 + Visual P11 · เกจแถบเขียวยืนยันผลซ้ำอีกชั้น"),
         ("Point ④ Fail-safe", "เส้นเยื้อง หรือเข็มออกนอกแถบเขียว = ผิดปกติ → ขันแน่น/แจ้งช่างตั้งค่าใหม่ · เส้นเลือน = ไม่ผ่านตรวจ"),
         ("Point ⑤ 苦労点", "(A) Regulator ต้องปรับค่าตั้งได้ → ลากเส้นใหม่ทุกครั้งโดยผู้ได้รับมอบหมาย และจดค่าตั้ง  (B) สีต้องไม่ร่อนจากแรงสั่น")],
     "cost": "~100–300 บาท (Paint marker + เทปสีเขียว) [INFERENCE: M]",
     "result": "2.5 → 0.5 นาที/วัน [PROPOSED] = (2.5−0.5) × 26 วัน × 12 เดือน = 624 นาที/ปี × ค่าแรง [DATA REQUIRED] · Q: แรงกระบอกสูบคงที่",
     "yokoten": ["Relief valve Lock nut ไฮดรอลิก (H-K2) " + PLACE, "ปุ่มปรับ Speed controller " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "2D side view", "3:2", "checking lock nut and flange bolts by hand every day",
          STYLE_A + ", flat 2D side view. A worker twisting the lock nut under the handle of an air regulator with fingers, then checking flange bolts and pipe clamp nuts nearby with a wrench, vibration lines on the machine, unsure face. Caption box: '2.5 min per day; vibration turns the handle by itself'. Red X on the handle area. " + COLOR.format(accent="red", where="the regulator handle")),
         ("A1 After Overview", "B Technical Textbook", "Isometric", "3:2", "match marks across nut and body plus a green band on the gauge make loosening and set-point drift visible",
          STYLE_B + ", isometric three-quarter view. An air filter, regulator and lubricator set with a pressure gauge showing a green band at the set pressure; a straight yellow paint line runs across the regulator lock nut and body; flange bolts and pipe clamp nuts on the nearby pipe carry the same straight lines. Component labels with leader lines: A = regulator lock nut, B = flange bolts, C = pipe clamp nut, D = green band on gauge. An eye symbol shows inspection from the aisle. " + COLOR.format(accent="orange", where="the green band and the paint lines")),
         ("A2 Point Close-up", "B Technical Textbook", "2D side view", "1:1", "handle rotation moves the paint segment and the needle leaves the green band together",
          "Technical diagram, square format, 2D side view. Left panel 'OK': regulator lock nut with paint line straight, gauge needle inside the green band. Right panel 'NG': lock nut and handle rotated by vibration (small curved arrow), paint segment offset, gauge needle moved outside the green band. Labels: A = handle, B = lock nut, C = paint line, D = gauge, E = green band. Flat grays. " + COLOR.format(accent="orange", where="the offset segment and the needle in the NG panel"))],
     "principles": [
         ("Source fact", "PDF p.39, p.44, p.49", "Lock nut กันค่าตั้งเปลี่ยนจากแรงสั่น · แถบเขียวที่ค่าตั้ง · ตรวจโบลต์/ที่ยึดท่อ", "ใช้เกณฑ์ต้นฉบับ", "Equipment Skills Training – Pneumatic", "[FACT]"),
         ("Idea Pattern", "PT-3", "Visual Control ‘อย่าวัด จงกำหนด’", "เส้นสี + แถบเขียว แทนการลองขัน", "BP1 p.102", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "Regulator ต้องปรับได้ → Eliminate การคลายไม่ได้ → Change วิธีตรวจ", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไมค่าตั้งเคลื่อน? Handle หมุนเอง → ทำไม? Lock nut คลายจากแรงสั่น (p.39) → ทำไม? ไม่มีวิธีเห็นการคลายระหว่างรอบตรวจ", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("Case reference", "KRK-CBI-154", "ความหลวมที่ซ่อนอยู่ แสดงให้เห็นในพริบตา", "แนวคิดเดียวกับ H-K2", "JIPM Case Book 1 p.154", "[FACT]")],
     "selfcheck": check()},

    {"id": "P-K4", "sys": "pn", "std": "P03 · ต้นทางระบบลม", "kind": "SOC", "priority": "P2", "resp": "Engineer / Utility",
     "before_min": None, "after_min": None, "occ": None, "cost_max": None, "confidence": "Level 3 · หลักวิศวกรรมทั่วไป ต้องออกแบบตามอัตราไหลจริง",
     "title": "Drain separator ที่ท่อหลัก 『ตัดน้ำที่ต้นทาง』",
     "summary": "ลดน้ำในลมอัด 『ที่ต้นทาง!』 → ทุกเครื่อง Drain น้อยลง วาล์ว/กระบอกสูบไม่เป็นสนิม · งาน EEM/Utility ไม่ใช่งาน AM · Confidence: Level 3",
     "workflow": ["① น้ำมาจากลมอัดต้นทาง ทุกเครื่องต้อง Drain ทุกวัน", "② น้ำ/สนิมจากท่อหลักเข้าวาล์วและกระบอกสูบ", "③ แก้ที่ปลายทางทีละเครื่อง (P-K1)"],
     "problem_quant": "Drain ทุก FRL ทุกวัน [FACT PDF p.44] · น้ำ → สนิมในท่อ ท่อตัน วาล์วติด ลมรั่ว Water hammer [FACT p.42] · ปริมาณน้ำต่อวัน [DATA REQUIRED]",
     "ideas": ["อยากหยุดน้ำก่อนเข้าเครื่อง", "อยากให้ทุกเครื่องได้ประโยชน์จากจุดเดียว", "อยากวัดได้ว่าแก้ได้ผล (น้ำในถ้วยลดลง)"],
     "mechanism": "ติด Drain separator หลังถังเก็บลม + Auto drain ที่จุดต่ำของท่อหลัก · ท่อแยกเข้าเครื่องต่อจากด้านบนของท่อหลัก [FACT p.36–37: Drain separator / Dehumidifier เป็นอุปกรณ์กรอง] [PROPOSED]",
     "points": [
         ("Point ① 力 กำลัง", "ใช้การไหลของลมเอง (เปลี่ยนทิศ/ลดความเร็ว) แยกหยดน้ำ — Drain separator ไม่มีชิ้นส่วนเคลื่อนที่ [INFERENCE: H]"),
         ("Point ② 構造 โครงสร้าง", "A Drain separator หลังถังเก็บลม  B Auto drain ที่จุดต่ำ  C ท่อแยกเข้าเครื่องต่อจากด้านบนท่อหลัก [INFERENCE: H]  D ขวด/ถังรับน้ำ"),
         ("Point ③ 原理 หลักการ", "หยดน้ำหนักกว่าอากาศ เลี้ยวไม่ทันจึงแยกตกลง + ท่อลาดลงสู่จุด Drain [INFERENCE: H] · กำจัดที่ต้นเหตุ (Eliminate)"),
         ("Point ④ Fail-safe", "Auto drain ต้นทางเสีย → FRL ที่เครื่องยังเป็นด่านที่ 2 · คงการตรวจ Drain รายวันไว้จนพิสูจน์ผลด้วยข้อมูล"),
         ("Point ⑤ 苦労点", "(A) เลือกขนาดตามอัตราไหลจริง ไม่ให้แรงดันตก (ท่อเล็ก/ยาว → แรงดันตก p.41)  (B) จุดติดตั้งต้องเข้าถึงง่าย ไม่สร้าง HTA ใหม่")],
     "cost": "[DATA REQUIRED] ตามขนาดท่อ/อัตราไหล — อาจเกิน 5,000 บาท → เสนอเป็นงบ EEM/Utility",
     "result": "วัดผล: ปริมาณน้ำที่ Drain ต่อวันที่ FRL ก่อน/หลัง [DATA REQUIRED] · เป้า: Drain รายวันเปลี่ยนเป็นตรวจตามรอบ [PROPOSED] · Q: วาล์ว/กระบอกสูบสนิมน้อยลง (p.42) · ต้องมี Baseline ก่อนคำนวณเงิน",
     "yokoten": ["ระบบลมอาคารอื่น " + PLACE, "ห้อง Compressor ทุกชุด " + PLACE],
     "prompts": [
         ("B1 Before", "A Kaizen Cartoon", "2D side view", "3:2", "wet compressed air from the main line forces daily draining at every machine",
          STYLE_A + ", flat 2D side view. A compressor and receiver tank on the left feeding a long main air pipe with water droplets inside, branch pipes dropping to three machines, each with a filter bowl full of water and a worker draining it, rust flakes in a valve inset. Caption box: 'every FRL drained every day'. Red X on the water entering the branches. " + COLOR.format(accent="red", where="the water droplets in the branches")),
         ("A1 After Overview", "B Technical Textbook", "2D side view", "3:2", "a drain separator removes water at the source; branches take air from the top of a sloped main line",
          STYLE_B + ", flat 2D side view. Compressor, receiver tank, then a drain separator with an auto drain to a collection bottle; the main line slopes slightly down toward a low-point auto drain; branch pipes rise from the top of the main line before dropping to three machines with nearly dry filter bowls. Component labels with leader lines: A = drain separator, B = low-point auto drain, C = top take-off branch, D = collection bottle. Bold arrows for air flow, small drops falling only at A and B. " + COLOR.format(accent="orange", where="the drain separator")),
         ("A2 Point Close-up", "B Technical Textbook", "Cross-section", "1:1", "sharp change of flow direction makes heavier water droplets separate and fall (inertia)",
          "Cutaway cross-section technical diagram, square format. Inside a drain separator: incoming air turns sharply around a baffle; water droplets continue straight, hit the wall and run down into the bottom bowl; dry air leaves at the top outlet. Curved arrows for air, straight dotted lines for droplets, drops collecting above the drain. Labels: A = inlet, B = baffle, C = outlet, D = water bowl, E = auto drain. Hatching on cut walls. " + COLOR.format(accent="orange", where="the baffle"))],
     "principles": [
         ("Source fact", "PDF p.36–37, p.41–42, p.44", "Drain separator/Dehumidifier เป็นอุปกรณ์กรอง · ปัญหาจาก Drain · Drain ทุกวัน", "เหตุผลของการแก้ที่ต้นทาง", "Equipment Skills Training – Pneumatic", "[FACT]"),
         ("Idea-Design", "ID-11", "ECR: Eliminate ก่อน", "นี่คือขั้น Eliminate ของปัญหาน้ำ (ราก) ส่วน P-K1 คือ Reduce ที่ปลายทาง", "KT2 pp.91-100", "[INFERENCE: H]"),
         ("9 Principles", "① 真因", "Why × 3", "ทำไมทุกเครื่องมีน้ำ? ลมอัดกลั่นตัวตอนเย็น → ทำไม? ความชื้นจาก Compressor ไม่ถูกแยกก่อนกระจาย → ทำไม? ไม่มีอุปกรณ์แยกน้ำ/จุด Drain ที่ท่อหลักเพียงพอ", "idea-kaizen V1.6", "[INFERENCE: M]"),
         ("6 Factors", "Environment / Design", "สภาพแวดล้อม · จุดอ่อนการออกแบบ", "แก้ที่ระบบ (EEM) ไม่ใช่เพิ่มงาน AM", "AM Standard · Forced_Deterioration", "[FACT]"),
         ("Low-Cost rule", "⑦", "≤ 5,000 บาท", "อาจเกินเกณฑ์ → แยกเป็นโครงการ EEM/Utility", "idea-kaizen V1.6", "[INFERENCE: M]")],
     "selfcheck": check(quantified=0)},
]
